# Generated by Django 3.0.2 on 2020-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
